### ISSUE TITLE
Getting current time isn't necessarily harmless

### ISSUE THREAD

**Issue by harrysarson** [ianmackenzie/elm-script#25]
Hi,

The README talks about the harmless things scripts can do by default which includes getting the current time. However, due to the spectre vulnerability accuracy timing information can be used by otherwise sandboxed code to access secrets. 

Unlikely this is that relevant here, but I thought worth flagging just to be on the safe side.

**Comment by ianmackenzie** [comment]
It's a valid point! I note that [Deno has a dedicated `--allow-hrtime` option for high-resolution timing](https://deno.land/manual/getting_started/permissions), and the `GetCurrentTime.elm` example works fine (at least on Windows, haven't checked other platforms) even with that flag not set - so I'm guessing that Elm's implementation of `Time.now` (which `Script.getCurrentTime` uses internally) doesn't access a high-resolution clock. If that is the case, do you think this is still a concern?

**Comment by harrysarson** [comment]
Aha `Time.now()` uses `Date.now()` under the hood. I don't know the default precision on it though.

**Comment by ianmackenzie** [comment]
I just realized that even though I'm pretty sure Deno's `Date.now()` implementation does its own rounding to defeat timing attacks, Elm's `Posix` type is based on integer milliseconds anyways! So calling `Script.getCurrentTime` will only ever allow for 1 millisecond precision (which seems to be a common cutoff that browsers use to defeat timing attacks/fingerprinting) regardless of what precision `Date.now()` returns. So I'm fairly confident that this wouldn't be an effective attack vector.
